GRIDSIZE = 4
SEARCH_RADIUS_CELL = 1
assert SEARCH_RADIUS_CELL < GRIDSIZE / 2
NUM_LATTICE_STEPS = 20
LATTICE_PLOT_PERIOD = 10
FIELD_REMOVE_RATIO = 0.0

VALID_BUILDSTRINGS = ["mono", "dual"]
VALID_FIELDSTRINGS = ["on", "off", "all"]
BUILDSTRING = "dual"
FIELDSTRING = "on"
