DIR_DATA = 'data'
DIR_MODELS = 'models'

CPU_THREADS = 8
BATCH_SIZE = 4

SYNTHETIC_DIM = 8
SYNTHETIC_SAMPLES = 10000
SYNTHETIC_NOISE_VALID = ['symmetric']
SYNTHETIC_SAMPLING_VALID = ['balanced']
SYNTHETIC_DATASPLIT = ['balanced']

DATA_CHOICE = 'mnist'

# HYPERPARAMETERS
# For threshold 0.4
#   2.0 -> 65.5%, 5.0 -> 68.6%, 20.0 -> 67.5%, 200.0 -> 65.6%
MNIST_BINARIZATION_CUTOFF = 0.4
BETA = 5.0
