DIR_DATA = 'data'
DIR_MODELS = 'models'

CPU_THREADS = 8
BATCH_SIZE = 4

SYNTHETIC_DIM = 8
SYNTHETIC_SAMPLES = 10000
SYNTHETIC_NOISE_VALID = ['symmetric']
SYNTHETIC_SAMPLING_VALID = ['balanced']
SYNTHETIC_DATASPLIT = ['balanced']

DATA_CHOICE = 'mnist'
MNIST_BINARIZATION_CUTOFF = 0.4
